### ISSUE TITLE
[Feature] Alert while user's nick appears

### ISSUE THREAD

**Issue by sshbio** [rcr/rirc#16]
First, thank you ___a lot___ for this wonderful irc client!

A proposition: use a print a terminal bell (as in `printf '\a'`) while the user's nick is being quoted.

This would trigger my `tmux`, then `st`, then `dwm`, to produce this:

In tmux, bash is in alert state:

![2016-03-31-143354_1366x768_scrot2](https://cloud.githubusercontent.com/assets/7250745/14175733/4b96d594-f74d-11e5-90a8-a945f679d6d2.png)

In dwm, tag 1 is in alert state:

![2016-03-31-132615_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/14174373/34dff46a-f744-11e5-9452-9a14d41ee01f.png)

**Comment by sshbio** [comment]
Oh, that is actually already implemented!  I just did not have any luck with people sending my nick just whil I came back to irc.

Anyway, I had to thank you for this marvellous free software.

**Comment by rcr** [comment]
Thanks! There's still a ton of work to do and I haven't been spending as much time as I'd like on it for the past few months but I've got a whole raft of improvements and fixes coming soon.

**Comment by sshbio** [comment]
This is great news!  It works mostly well for me right now.
