### ISSUE TITLE
Implementing logs

### ISSUE THREAD

**Issue by josuah** [rcr/rirc#19]
If logs must be created, there will be a directory to put them in, like `rirc -l path/to/log-dir`.  Inside of it, there can be either a flat structures with `irc.server-name.net_#channel-name.log` or a tree, like: `irc.server-name.net/#channel-name.log`.  For now, I use the former.  I am not sure what permission I should put for the logs.

Rirc sends everything it to print out to `newline` and `newlinef()`, which both use `_newline()`.  There could be a call to an `appendlog()` function in there that would write each line at the end of the log file.  I'll work on this on the [logs branch](http://github.com/sshbio/rirc/tree/logs).

**Comment by sshbio** [comment]
If logs must be created, there will be a directory to put them in, like `rirc -l path/to/log-dir`.  Shell alias would come usefull then.  Insiie of it, there can be either a flat structures with `irc.server-name.net_#channel-name.log` or a tree, like: `irc.server-name.net/#channel-name.log`.

**Comment by sshbio** [comment]
If you we ever get code from suckless, rirc may need to change its license to MIT, as it is the one ii uses:
http://git.suckless.org/ii/tree/LICENSE

I'm not familiar yet with licences yet.

**Comment by sshbio** [comment]
Rirc has the nice characteristic to send everything it wants to write out to newline and `newlinef()`.  There could be a coll to a `appendlog()` function in there that would write each line at the end of the correctly named log file.  I'll work on this on the [logs branch](http://github.com/sshbio/rirc/tree/logs).

**Comment by sshbio** [comment]
Not sure what permission I should put for the logs.  Public read access or not is my question.

**Comment by sshbio** [comment]
Here we go!  A very experimental log feature! :3

The logs messages are very basic, but more important: the whole implementation is messy.  Quite a hack, so I'm not making a pull request right now.

**Comment by sshbio** [comment]
I got one segfault, and some empty logs files, though.

**Comment by rcr** [comment]
You should be checking return codes for every single system call; mkdir, fopen, etc. Example if fopen fails due to permissions it returns NULL, which you pass to the first argument of fprintf

**Comment by sshbio** [comment]
It needs more rigor.  And thank you for looking at this.  I will try write correct code now that I have this basic draft.

**Comment by josuah** [comment]
Long term solution: using a bouncer, or even [ii](http://tools.suckless.org/ii) as this is a program that only implements logs: No bloat introduced to rirc, kept simple and unencumbered.

**Comment by rcr** [comment]
Yeah, agreed. I took a look at adding logs a while back but it's a much bigger task than it sounds like. I think using existing tools like you said is a better idea
