### ISSUE TITLE
Option to display notices in the server buffer

### ISSUE THREAD

**Issue by strafe** [rcr/rirc#32]
Had a quick peak at what Weechat is doing, and it seems a little more in-depth than just putting all notices in the server buffer, but close enough.

I hate connecting to freenode and getting private message buffers opened from `freenode-connect` and `NickServ` every time. Weechat seems to redirect these to the server buffer if a private message buffer does not currently exist for that nick. But a config setting to just always send them to the server buffer would suffice pretty nicely.

**Comment by rcr** [comment]
Yeah, I agree. NOTICE messages are typically automated and shouldn't be creating channel buffers. I wouldn't even make this configurable. NOTICE messages from targets that don't have an open buffer should print to the server buffer with some indication that it's a notice and who it's from.

**Comment by strafe** [comment]
> Yeah, I agree. NOTICE messages are typically automated and shouldn't be creating channel buffers. I wouldn't even make this configurable. NOTICE messages from targets that don't have an open buffer should print to the server buffer with some indication that it's a notice and who it's from, marked urgent.

That sounds perfect.

**Comment by rcr** [comment]
This is now fixed in v0.1.5
