### ISSUE TITLE
Green text if > is first character in a line

### ISSUE THREAD

**Issue by dforsyth** [rcr/rirc#4]
It would be cool if rirc would green text if > is the first character in a line

**Comment by rcr** [comment]
[sixthgear](http://github.com/sixthgear) said if I implement this he'll beat me up

**Comment by sixthgear** [comment]
I would never speak like this to anyone, especially my friend rcr.

**Comment by dforsyth** [comment]
dONT YOU CARE ABOUT THE USERS?
