### ISSUE TITLE
Allow for default config file.

### ISSUE THREAD

**Issue by howardroark** [rcr/rirc#5]
You have done an amazing job here.  It all feels so comfortable.  It would be awesome if you could supply a default config in the user homedir.  Something object based like YAML or JSON.

Something where you could supply the sever to connect to and the list of default channels to join.  Basically all the grunt work.  I could tie this into a development vm build process where it auto joins the channels related to the project at hand.

I find a lot of companies are staffing IRC channels.  Like the Stripe payment system.

**Comment by rcr** [comment]
Thanks!

There are a few comments strewn about the source about this, I've been meaning to get to it for a while.

I think the first step would be collecting any configurable globals into a header file at the project root, e.g. config.h, so configuration would be done by recompiling.

The next step would be to implement some sort of runtime config parser like you mentioned that looks for ~/.rircrc or something. YAML might be a good idea.

**Comment by thyssentishman** [comment]
@rcr, I'd like to help implement this feature. Is it still something you'd like to work on? I want to package rirc for OpenBSD and having a runtime config so that users don't have to depend on the settings I packaged rirc with would be very nice.
