### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by howardroark** [rcr/rirc#6]
What is keyboard shortcut to switch between channels?

Could you maybe update the README with a basic matrix of keyboard shortcuts? :) :)

Thanks!

**Comment by rcr** [comment]
Right now it's pageup/pagedown. This was just a temporary thing I set them to while I was testing the channel movement stuff that I haven't gotten around to changing. I think ctrl+p and ctrl+n for previous/next channel would make more sense.

Right now there's not a whole lot of keybinds, but you're right, I should update the README with the current list. I should probably update the screenshots too, they're a full year out of date and a few things have changed :)
