### ISSUE TITLE
Would you be willing to support OSX?

### ISSUE THREAD

**Issue by howardroark** [rcr/rirc#9]
Hey!

Any chance you would be up for porting this to "homebrew"?  I have tried compiling it on OSX but it lacks the `-fsanitize` clang option.  If there was a binary available for OSX's Darwin BSD variant, it could easily be added to the "homebrew" repo.

Then OSX users could just do `brew install rirc` :)

**Comment by rcr** [comment]
Long overdue but rirc supports osx
